In [5]:
import numpy as np
import pandas as pd

In [6]:
pd.__version__

'1.4.4'

In [7]:
df= pd.read_csv(r'C:\Users\hp\Desktop\housing.csv')
pd.DataFrame(df)
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  media

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [9]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [10]:
nearbaydf= df[df['ocean_proximity'] == 'NEAR BAY']
nearbaydf['median_house_value'].mean()

259212.31179039303

In [11]:
tbmean= df['total_bedrooms'].mean()
tbmean

537.8705525375618

In [12]:
df['tbnew']= df['total_bedrooms'].fillna(tbmean)
df['tbnew'].isna().sum()
df['tbnew'].mean()


537.8705525375639

In [13]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity', 'tbnew'],
      dtype='object')

In [14]:
islanddf= df[df['ocean_proximity'] == 'ISLAND']
X= islanddf[['housing_median_age', 'total_rooms', 'total_bedrooms']] 
X

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [15]:
X1 = X.to_numpy()
X1.shape


(5, 3)

In [16]:
T= X1.transpose()
T.shape

(3, 5)

In [17]:
XTX= np.dot(T, X1)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [18]:
inv= np.linalg.inv(XTX)
z= np.dot(inv, T)
z

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [19]:
y= np.array([950, 1300, 800, 1000, 1300])
w= np.dot(z,y)
w


array([23.12330961, -1.48124183,  5.69922946])